version: '4.0'

services:
  n8n:
    image: n8nio/n8n:1.48.3
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_GIT_CREDENTIALS=your_github_access_token
    volumes:
      - ~/.n8n:/home/node/.n8n

volumes:
  n8n_data:
